#!/usr/bin/env python3
"""Measure QR decode against altitude - REAL gz render, REAL perception code.

    bash sim/tools/measure_alt.sh          # brings gz + the bridge up, runs this
    python3 sim/tools/measure_alt.py       # if you already have both running

It listens on /cam60 ... /cam20: static cameras that sit at fixed altitudes,
each boresighted on the QR pad down the dive's own look-down angle. There is no
aircraft and no flight involved - the question here is only "at what altitude
does the code stop being readable", and a static rig answers it without the
run-to-run scatter of a real dive.

⚠️ WHERE THE ALTITUDES COME FROM. They are NOT a list in this file. They are
   read out of sim/worlds/qr_measure.sdf, together with the pad, and every
   altitude, ground distance and slant range below is computed from the poses
   actually in that world.

   This matters because of how the table used to be produced: the tool
   hard-coded ALTS = [60, 50, ...] and a 55 degree angle, while the world that
   generated those cameras WAS NEVER COMMITTED. The numbers in the README were
   therefore unreproducible - the apparatus existed only on one machine. The
   world is now generated by build_world.py --measure and committed, and this
   file reads it, so the two cannot drift apart.
"""
import math
import os
import sys
import xml.etree.ElementTree as ET

# ⚠️ The repository root is derived FROM THIS FILE'S OWN LOCATION - never
#    written as an absolute path. It used to be hard-coded as
#    "/mnt/c/Users/<name>/...", which both failed on anyone else's machine
#    and leaked a username into a public repository.
SIM = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, SIM)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cam_params  # the single source of camera parameters (reads model.sdf)

import logging
logging.disable(logging.WARNING)

import numpy as np
import cv2
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

from processes.perception import PerceptionProcess

WORLD = os.path.join(SIM, "sim", "worlds", "qr_measure.sdf")
WANT = 4                      # frames to collect per camera
OUT = "/tmp/alt"
os.makedirs(OUT, exist_ok=True)


def read_rig(world_path):
    """Read the measurement cameras and the pad out of the world.

    Returns a list of (topic, altitude_m, ground_distance_m, slant_range_m),
    highest camera first. Fails LOUDLY if the world is missing rather than
    falling back to a built-in list: a silent default here would report a
    table that describes a rig nobody actually rendered.
    """
    if not os.path.exists(world_path):
        raise SystemExit(
            "ERROR: measurement world not found: %s\n"
            "Generate it first:\n"
            "  python3 sim/tools/build_world.py --measure \\\n"
            "      ~/PX4-Autopilot/Tools/simulation/gz/worlds/default.sdf \\\n"
            "      sim/worlds/qr_measure.sdf" % world_path)

    world = ET.parse(world_path).getroot().find("world")

    pad = None
    for inc in world.findall("include"):
        name = inc.find("name")
        if name is not None and name.text == "qr_pad":
            pad = [float(v) for v in inc.find("pose").text.split()]
    if pad is None:
        raise SystemExit("ERROR: no qr_pad in %s" % world_path)

    rig = []
    for model in world.findall("model"):
        sensor = None
        for s in model.iter("sensor"):
            if s.get("type") == "camera":
                sensor = s
        if sensor is None:
            continue
        topic = sensor.find("topic")
        if topic is None or not topic.text.startswith("cam"):
            continue
        pose = [float(v) for v in model.find("pose").text.split()]
        ground = math.hypot(pad[0] - pose[0], pad[1] - pose[1])
        rig.append((topic.text, pose[2], ground, math.hypot(ground, pose[2])))

    if not rig:
        raise SystemExit("ERROR: no cam* cameras in %s - was it built with "
                         "--measure?" % world_path)
    return sorted(rig, key=lambda r: -r[1])


class Q:
    def __init__(self):
        self.items = []

    def put_nowait(self, x):
        self.items.append(x)

    def get_nowait(self):
        raise Exception("empty")


class M(Node):
    def __init__(self, rig):
        super().__init__("alt_measure")
        self.b = CvBridge()
        self.p = PerceptionProcess(Q(), Q())
        self.rig = rig
        keys = [r[0] for r in rig]
        self.n = {k: 0 for k in keys}
        self.hit = {k: 0 for k in keys}
        self.px = {k: 0 for k in keys}
        self.inav = {k: 0 for k in keys}
        for topic, alt, _, _ in rig:
            self.create_subscription(Image, "/" + topic,
                                     self._cb(topic, alt), 1)

    def _cb(self, topic, alt):
        def cb(msg):
            if self.n[topic] >= WANT:
                return
            f = self.b.imgmsg_to_cv2(msg, desired_encoding="bgr8")
            self.n[topic] += 1
            vis = f.copy()
            self.p.result_queue = Q()
            self.p._process_qr(vis, set())
            r = self.p.result_queue.items
            if r:
                self.hit[topic] += 1
                b = r[0]["box"]
                self.px[topic] = max(self.px[topic], max(b[2], b[3]))
                if r[0].get("in_av"):
                    self.inav[topic] += 1
                if self.hit[topic] == 1:
                    self.p._draw_hud(vis, vis.shape[1], vis.shape[0], 30.0)
                    cv2.imwrite(os.path.join(OUT, "alt%02d.png" % alt), vis)
            elif self.n[topic] == WANT:
                self.p._draw_hud(vis, vis.shape[1], vis.shape[0], 30.0)
                cv2.imwrite(os.path.join(OUT, "alt%02d_nodecode.png" % alt), vis)
        return cb

    def done(self):
        return all(v >= WANT for v in self.n.values())


def main():
    rig = read_rig(WORLD)

    rclpy.init()
    node = M(rig)
    t = 0.0
    while rclpy.ok() and not node.done() and t < 45.0:
        rclpy.spin_once(node, timeout_sec=0.2)
        t += 0.2

    missing = [k for k, v in node.n.items() if v == 0]

    # ⚠️ This used to be written out as `1920 / math.degrees(0.8954)`. If the
    #    camera parameter changed in model.sdf, this table would silently
    #    produce a wrong "theoretical px" column. It now comes from the single
    #    source (cam_params.py).
    ppd = cam_params.pixels_per_degree()
    print()
    print("=" * 78)
    print("  QR DECODE vs ALTITUDE  (gz render, real perception code)")
    print("  V1 QR, 2-module quiet zone, %.0f degree look-down"
          % math.degrees(math.atan2(rig[0][1], rig[0][2])))
    print("  world: %s" % WORLD)
    print("=" * 78)
    print("  %6s %8s %8s %9s %8s %8s" %
          ("alt", "ground", "slant", "theory px", "measured", "decode"))
    print("  " + "-" * 60)
    for topic, alt, ground, slant in rig:
        # Angular size of the 1 m QR at this slant range, times pixels/degree.
        teo = math.degrees(2 * math.atan(1.0 / slant)) * ppd
        ratio = "%d/%d" % (node.hit[topic], node.n[topic])
        print("  %5.0f m %7.1f m %7.1f m %8.0f %8s %8s%s" %
              (alt, ground, slant, teo, node.px[topic] or "-", ratio,
               "  (AV %d)" % node.inav[topic] if node.hit[topic] else ""))

    ok = [alt for topic, alt, _, _ in rig if node.hit[topic] > 0]
    print()
    if missing:
        # Without this the table would show a confident 0/0 for a camera whose
        # frames never arrived, which reads exactly like "does not decode".
        print("  ⚠️ NO FRAMES ARRIVED ON: %s" % " ".join(missing))
        print("     Is the ros_gz_bridge running for every topic? See "
              "measure_alt.sh")
    if ok:
        print("  HIGHEST ALTITUDE THAT DECODES: %.0f m" % max(ok))
        print("     (few frames per step; instability near the threshold is normal)")
    else:
        print("  NO DECODE AT ANY ALTITUDE")
    node.destroy_node()
    rclpy.shutdown()
    return 0 if ok and not missing else 2


if __name__ == "__main__":
    sys.exit(main())
